# Generated by Django 5.0.1 on 2024-01-18 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citydata',
            old_name='long',
            new_name='lon',
        ),
    ]
