# Generated by Django 5.0.1 on 2024-01-23 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_rename_long_citydata_lon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citydata',
            name='state',
        ),
    ]
