# Generated by Django 5.0.1 on 2024-01-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_remove_citydata_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='citydata',
            name='slug',
            field=models.CharField(default='nag', max_length=170),
            preserve_default=False,
        ),
    ]
